name: Check

on:
  pull_request:
    branches: ["*"]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Installling dependencies
        run: npm install --workspaces

      - name: ESLint check
        run: npm run lint:check --workspaces

      - name: Format with prettier
        run: npx prettier --check --ignore-path .gitignore .

      - name: Test
        run: npm run test -w backend
        env:
          NODE_ENV: test

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: javascript, typescript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

      - name: Build frontend
        run: npm run build -w frontend
        env:
          NODE_ENV: production

      - name: Build backend
        run: npm run build -w backend
        env:
          NODE_ENV: production

      - name: Send coverage report to Codecov
        uses: codecov/codecov-action@v2
